import Image from "next/image";
import Link from "next/link";
import { ReviewStatus } from "@prisma/client";
import { z } from "zod";
import { parseAdminListQuery, requireAdmin } from "@/lib/admin";
import { prisma } from "@/lib/prisma";
import { AdminProductReviewActions } from "@/components/admin-product-review-actions";

const labels:Record<string,string>={PUBLISHED:"Tayang",PENDING:"Menunggu persetujuan",HIDDEN:"Tersembunyi"};
export default async function ProductReviewsAdmin({searchParams}:{searchParams:{q?:string;status?:string;rating?:string;product?:string;foto?:string;page?:string}}){
 await requireAdmin();
 const list=parseAdminListQuery(searchParams);
 const extra=z.object({rating:z.preprocess((value)=>value===""||value===undefined?undefined:value,z.coerce.number().int().min(1).max(5).optional()),product:z.string().max(120).optional(),foto:z.enum(["1"]).optional()}).parse({rating:searchParams.rating,product:searchParams.product,foto:searchParams.foto});
 const page=list.page;const status=Object.values(ReviewStatus).includes(list.status as ReviewStatus)?list.status as ReviewStatus:undefined;
 const where={...(status?{status}:{}),...(extra.rating?{rating:extra.rating}:{}),...(extra.product?{productId:extra.product}:{}),...(extra.foto==="1"?{photos:{some:{}}}:{}),...(list.q?{OR:[{displayName:{contains:list.q,mode:"insensitive" as const}},{body:{contains:list.q,mode:"insensitive" as const}}]}:{})};
 const [rows,total,products]=await Promise.all([prisma.review.findMany({where,include:{product:{select:{name:true,slug:true}},photos:{orderBy:{sortOrder:"asc"}},orderItem:{include:{order:{select:{orderNumber:true,customerName:true,customerEmail:true}}}}},orderBy:{createdAt:"desc"},skip:(page-1)*20,take:20}),prisma.review.count({where}),prisma.product.findMany({select:{id:true,name:true},orderBy:{name:"asc"}})]);
 return <><div className="admin-page-heading"><div><p className="eyebrow">Ulasan pembeli terverifikasi</p><h1>Ulasan produk</h1></div><span>{total} ulasan</span></div>
 <form className="admin-search"><input className="admin-input" name="q" placeholder="Cari nama atau isi ulasan" defaultValue={searchParams.q}/><select name="status" defaultValue={status??""}><option value="">Semua status</option>{Object.values(ReviewStatus).map((value)=><option key={value} value={value}>{labels[value]}</option>)}</select><select name="rating" defaultValue={searchParams.rating??""}><option value="">Semua bintang</option>{[5,4,3,2,1].map((value)=><option key={value} value={value}>{value} bintang</option>)}</select><select name="product" defaultValue={searchParams.product??""}><option value="">Semua produk</option>{products.map((product)=><option key={product.id} value={product.id}>{product.name}</option>)}</select><label className="admin-check"><input type="checkbox" name="foto" value="1" defaultChecked={searchParams.foto==="1"}/> Dengan foto</label><button className="secondary-button">Filter</button></form>
 <section className="admin-card">{rows.length?rows.map((review)=><article className="admin-product-review" key={review.id}><header><div><Link href={"/produk/"+review.product.slug} target="_blank">{review.product.name}</Link><span> · {labels[review.status]}</span></div><time>{new Intl.DateTimeFormat("id-ID",{dateStyle:"medium",timeZone:"Asia/Jakarta"}).format(review.createdAt)}</time></header><p><b>{review.displayName}</b> · {review.rating}/5 ★</p><p>{review.body}</p>{review.photos.length>0&&<div className="review-photo-previews">{review.photos.map((photo)=><a href={photo.url} target="_blank" rel="noreferrer" key={photo.id}><Image src={photo.url} alt="Foto ulasan" width={96} height={96}/></a>)}</div>}<p className="admin-muted">Pesanan <Link href={"/admin/pesanan/"+review.orderItem.order.orderNumber}>{review.orderItem.order.orderNumber}</Link> · {review.orderItem.order.customerName} ({review.orderItem.order.customerEmail})</p><AdminProductReviewActions id={review.id} status={review.status} reply={review.sellerReply}/></article>):<p>Belum ada ulasan produk yang cocok dengan filter ini.</p>}<div className="admin-pagination">{page>1&&<a href="?page=1">Halaman pertama</a>}<span>Halaman {page} · {total} ulasan</span>{page*20<total&&<a href={"?page="+(page+1)}>Berikutnya →</a>}</div></section></>;
}
