"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { requireAdmin } from "@/lib/admin";
import { persistSlugRedirect } from "@/lib/seo-admin";
const settingSchema=z.object({titleTemplate:z.string().min(1).max(200),separator:z.string().min(1).max(10),siteName:z.string().min(1).max(100),defaultDescription:z.string().max(300),defaultOgImageUrl:z.string().max(2000),googleVerification:z.string().max(250),bingVerification:z.string().max(250),ga4Id:z.string().max(50),metaPixelId:z.string().max(50),business:z.object({name:z.string().max(100),logoUrl:z.string().max(2000),address:z.string().max(500),telephone:z.string().max(60),openingHours:z.string().max(200),priceRange:z.string().max(50),socialLinks:z.array(z.string().url()).max(20)})});
export async function saveGlobalSeo(formData:FormData){await requireAdmin();let raw:unknown;try{raw=JSON.parse(String(formData.get("settings")||"{}"));}catch{redirect("/admin/seo?tab=umum&error=Data%20SEO%20tidak%20valid");}const parsed=settingSchema.safeParse(raw);if(!parsed.success)redirect("/admin/seo?tab=umum&error=Periksa%20format%20tautan%20dan%20pengaturan");await prisma.setting.upsert({where:{key:"seo"},create:{key:"seo",value:parsed.data as any},update:{value:parsed.data as any}});revalidatePath("/","layout");redirect("/admin/seo?tab=umum&success=Pengaturan%20SEO%20tersimpan");}
const path=z.string().trim().min(1).max(500).regex(/^\/(?!\/)[^?#\s]*$/);
export async function saveRedirect(formData:FormData){await requireAdmin();const parsed=z.object({id:z.string().optional(),fromPath:path,toPath:path,statusCode:z.coerce.number().refine(value=>value===301||value===302),isActive:z.boolean()}).safeParse({id:formData.get("id")||undefined,fromPath:formData.get("fromPath"),toPath:formData.get("toPath"),statusCode:formData.get("statusCode"),isActive:formData.get("isActive")==="on"});if(!parsed.success||parsed.data.fromPath===parsed.data.toPath)redirect("/admin/seo?tab=redirect&error=Jalur%20redirect%20tidak%20valid");const old=parsed.data.id?await prisma.redirect.findUnique({where:{id:parsed.data.id}}):null;if(parsed.data.id&&!old)redirect("/admin/seo?tab=redirect&error=Redirect%20tidak%20ditemukan");try{await persistSlugRedirect(parsed.data.fromPath,parsed.data.toPath,parsed.data.statusCode as 301|302);if(old&&old.fromPath!==parsed.data.fromPath)await prisma.redirect.delete({where:{id:old.id}});await prisma.redirect.update({where:{fromPath:parsed.data.fromPath},data:{isActive:parsed.data.isActive}});}catch{redirect("/admin/seo?tab=redirect&error=Redirect%20membentuk%20siklus%20atau%20sudah%20digunakan");}revalidatePath(parsed.data.fromPath);revalidatePath("/admin/seo");redirect("/admin/seo?tab=redirect&success=Redirect%20tersimpan");}
export async function deleteRedirect(formData:FormData){await requireAdmin();const id=z.string().min(1).safeParse(formData.get("id"));if(!id.success)return;await prisma.redirect.delete({where:{id:id.data}});revalidatePath("/admin/seo");redirect("/admin/seo?tab=redirect&success=Redirect%20dihapus");}
