import Link from "next/link";
import { requireAdmin } from "@/lib/admin";
import { prisma } from "@/lib/prisma";
import { getSeoSettings } from "@/lib/seo";
import { SeoSettingsForm } from "@/components/seo/seo-settings-form";
import { DeleteConfirmForm } from "@/components/cms/delete-confirm-form";
import { deleteRedirect,saveRedirect } from "@/app/admin/seo/actions";
import type { MediaOption } from "@/components/admin-ui";
const tabs=[["umum","Umum"],["bisnis","Bisnis lokal"],["verifikasi","Verifikasi dan analytics"],["sitemap","Sitemap"],["redirect","Redirect"],["404","Log 404"],["audit","Audit"]] as const;
export default async function AdminSeoPage({searchParams}:{searchParams:{tab?:string;edit?:string;from?:string;to?:string}}){
 await requireAdmin();const tab=tabs.some(([id])=>id===searchParams.tab)?searchParams.tab!:"umum";
 const [settings,media,redirects,logs,products,pages,posts,seoRows,emptyAlt,editing]=await Promise.all([getSeoSettings(),prisma.media.findMany({orderBy:{createdAt:"desc"},take:100}),prisma.redirect.findMany({orderBy:{createdAt:"desc"},take:300}),prisma.notFoundLog.findMany({orderBy:[{count:"desc"},{lastSeenAt:"desc"}],take:100}),prisma.product.findMany({select:{id:true,slug:true,name:true,shortDescription:true,description:true,images:{select:{alt:true}}},orderBy:{updatedAt:"desc"},take:1000}),prisma.page.findMany({select:{id:true,slug:true,title:true,blocks:true}}),prisma.blogPost.findMany({select:{id:true,slug:true,title:true,excerpt:true,content:true},orderBy:{updatedAt:"desc"},take:1000}),prisma.seoMeta.findMany({select:{entityType:true,entityId:true,seoTitle:true,metaDescription:true,focusKeyword:true}}),prisma.media.findMany({where:{alt:""},select:{id:true,path:true}}),searchParams.edit?prisma.redirect.findUnique({where:{id:searchParams.edit}}):Promise.resolve(null)]);
 const byEntity=new Map(seoRows.map((row)=>[`${row.entityType}:${row.entityId}`,row]));const incomplete=[...products.map((row)=>({type:"Produk",slug:row.slug,title:row.name,name:row.name,href:`/admin/produk/${row.id}`,meta:byEntity.get(`PRODUCT:${row.slug}`)})),...pages.map((row)=>({type:"Halaman",slug:row.slug,title:row.title,name:row.title,href:`/admin/halaman/${row.id}`,meta:byEntity.get(`PAGE:${row.slug}`)})),...posts.map((row)=>({type:"Artikel",slug:row.slug,title:row.title,name:row.title,href:`/admin/blog/${row.id}`,meta:byEntity.get(`BLOG_POST:${row.slug}`)}))].filter((row)=>!row.meta?.seoTitle||!row.meta?.metaDescription||!row.meta?.focusKeyword);
 return <><div className="admin-page-heading"><div><p className="eyebrow">Visibilitas pencarian</p><h1>SEO</h1></div></div><nav className="seo-tabs" aria-label="Pengaturan SEO">{tabs.map(([id,label])=><Link className={tab===id?"active":""} href={`/admin/seo?tab=${id}`} key={id}>{label}</Link>)}</nav>
 {(["umum","bisnis","verifikasi"] as string[]).includes(tab)&&<SeoSettingsForm initial={settings} media={media as MediaOption[]} tab={tab}/>}
 {tab==="sitemap"&&<section className="admin-card"><h2>Sitemap dan robots</h2><p>Sitemap diperbarui otomatis dari halaman, produk, kategori, dan artikel yang dapat diindeks.</p><p><a href="/sitemap.xml" target="_blank" rel="noreferrer">Buka sitemap.xml ↗</a></p><p><a href="/robots.txt" target="_blank" rel="noreferrer">Buka robots.txt ↗</a></p></section>}
 {tab==="redirect"&&<><form action={saveRedirect} className="admin-card seo-redirect-form"><h2>{editing?"Ubah redirect":"Tambah redirect"}</h2>{editing&&<input type="hidden" name="id" value={editing.id}/>}<label>Dari path<input className="admin-input" name="fromPath" defaultValue={editing?.fromPath||searchParams.from||"/lama"} required placeholder="/alamat-lama"/></label><label>Ke path<input className="admin-input" name="toPath" defaultValue={editing?.toPath||searchParams.to||"/"} required placeholder="/alamat-baru"/></label><label>Kode<select className="admin-input" name="statusCode" defaultValue={editing?.statusCode||301}><option value="301">301 · Permanen</option><option value="302">302 · Sementara</option></select></label><label><input type="checkbox" name="isActive" defaultChecked={editing?.isActive??true}/> Aktif</label><button className="buy-button">Simpan redirect</button></form><section className="admin-card"><h2>Redirect aktif dan nonaktif</h2><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Dari</th><th>Ke</th><th>Kode</th><th>Hit</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{redirects.map(row=><tr key={row.id}><td>{row.fromPath}</td><td>{row.toPath}</td><td>{row.statusCode}</td><td>{row.hits}</td><td>{row.isActive?"Aktif":"Nonaktif"}</td><td><div className="cms-fields"><Link className="secondary-button" href={`/admin/seo?tab=redirect&edit=${row.id}`}>Ubah</Link><a className="secondary-button" href={row.fromPath} target="_blank">Uji</a><DeleteConfirmForm id={row.id} action={deleteRedirect} message="Hapus redirect ini?"/></div></td></tr>)}</tbody></table></div>{!redirects.length&&<p>Belum ada redirect.</p>}</section></>}
 {tab==="404"&&<section className="admin-card"><h2>Path tidak ditemukan</h2><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Path</th><th>Jumlah</th><th>Terakhir terlihat</th><th>Referrer</th><th></th></tr></thead><tbody>{logs.map(row=><tr key={row.id}><td>{row.path}</td><td>{row.count}</td><td>{new Intl.DateTimeFormat("id-ID",{dateStyle:"medium",timeStyle:"short"}).format(row.lastSeenAt)}</td><td>{row.lastReferrer||"—"}</td><td><Link className="secondary-button" href={`/admin/seo?tab=redirect&from=${encodeURIComponent(row.path)}&to=%2F`}>Buat redirect</Link></td></tr>)}</tbody></table></div>{!logs.length&&<p>Belum ada log 404.</p>}</section>}
 {tab==="audit"&&<><section className="admin-card"><h2>Metadata belum lengkap</h2><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Jenis</th><th>Konten</th><th>Belum diisi</th><th></th></tr></thead><tbody>{incomplete.map((row,index)=><tr key={`${row.type}-${index}`}><td>{row.type}</td><td>{row.name}</td><td>{[!row.meta?.seoTitle&&"Judul SEO",!row.meta?.metaDescription&&"Deskripsi",!row.meta?.focusKeyword&&"Kata kunci"].filter(Boolean).join(", ")}</td><td><Link className="secondary-button" href={row.href}>Perbaiki</Link></td></tr>)}</tbody></table></div>{!incomplete.length&&<p>Semua konten memiliki judul, deskripsi, dan kata kunci.</p>}</section><section className="admin-card"><h2>Gambar tanpa teks alternatif</h2>{emptyAlt.map(row=><p key={row.id}>{row.path} · <Link href="/admin/media">Buka Media Library</Link></p>)}{!emptyAlt.length&&<p>Semua media memiliki teks alternatif.</p>}</section></>}
 </>;
}
