"use client";
import { useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { MediaPicker, type MediaOption } from "@/components/admin-ui";
import { saveProduct } from "@/app/admin/actions";
import { deleteProduct } from "@/app/admin/actions";
import { ConfirmButton } from "@/components/admin-ui";
import { SeoPanel } from "@/components/seo/seo-panel";
import type { SeoEntityType } from "@prisma/client";

type ImageRow = { url: string; alt: string; sortOrder: number; isPrimary: boolean; blendMultiply: boolean };
type VariantRow = { name: string; price: number; compareAtPrice: number | ""; stock: number; sku: string; sortOrder: number; isActive: boolean };
export function AdminProductForm({ categories, media, initial }: { categories: { id: string; name: string }[]; media: MediaOption[]; initial?: { id: string; name: string; slug: string; shortDescription: string; description: string; categoryId: string; status: "DRAFT"|"PUBLISHED"; isFeatured: boolean; images: { url: string; alt: string; sortOrder: number; isPrimary: boolean; blendMultiply: boolean }[]; variants: { name: string; price: number; compareAtPrice: number|null; stock: number; sku: string|null; sortOrder: number; isActive: boolean }[]; seo?:any } }) {
  const [name, setName] = useState(initial?.name ?? ""); const [slug, setSlug] = useState(initial?.slug ?? ""); const [slugEdited, setSlugEdited] = useState(Boolean(initial)); const [shortDescription,setShortDescription]=useState(initial?.shortDescription??"");
  const [images, setImages] = useState<ImageRow[]>(initial?.images ?? []); const [variants, setVariants] = useState<VariantRow[]>(initial?.variants.map((row)=>({...row,compareAtPrice:row.compareAtPrice??"",sku:row.sku??""})) ?? [{name:"S",price:99000,compareAtPrice:"",stock:3,sku:"",sortOrder:0,isActive:true},{name:"M",price:149000,compareAtPrice:"",stock:5,sku:"",sortOrder:1,isActive:true},{name:"L",price:199000,compareAtPrice:"",stock:4,sku:"",sortOrder:2,isActive:true}]); const [description,setDescription]=useState(initial?.description??"");
  const slugify=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
  function addImages(rows:MediaOption[]){const next=rows.map((row,index)=>{const existing=images.find((image)=>image.url===row.url);return existing?{...existing,sortOrder:index}:{url:row.url,alt:row.alt,sortOrder:index,isPrimary:images.length===0&&index===0,blendMultiply:false};});setImages(next);}
  return <form action={saveProduct} className="admin-card admin-form"><input type="hidden" name="id" value={initial?.id??""}/><input type="hidden" name="images" value={JSON.stringify(images.map((row,index)=>({...row,sortOrder:index})))}/><input type="hidden" name="variants" value={JSON.stringify(variants.map((row,index)=>({...row,sortOrder:index})))} />
    <div className="admin-form-grid"><label>Nama produk<input required name="name" value={name} onChange={(e)=>{setName(e.target.value);if(!slugEdited)setSlug(slugify(e.target.value));}} /></label><label>Slug<input required name="slug" value={slug} onChange={(e)=>{setSlugEdited(true);setSlug(slugify(e.target.value));}} /></label><label>Kategori<select name="categoryId" required defaultValue={initial?.categoryId??categories[0]?.id}>{categories.map((c)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Status<select name="status" defaultValue={initial?.status??"DRAFT"}><option value="DRAFT">Draf</option><option value="PUBLISHED">Terbit</option></select></label><label className="field-wide">Deskripsi singkat<input required name="shortDescription" value={shortDescription} onChange={e=>setShortDescription(e.target.value)}/></label><label className="field-wide">Deskripsi<textarea name="description" rows={6} required value={description} onChange={e=>setDescription(e.target.value)}/></label><label className="admin-check"><input type="checkbox" name="isFeatured" defaultChecked={initial?.isFeatured}/> Produk unggulan</label></div>
    <section className="admin-subsection"><div className="admin-section-head"><h2>Gambar produk</h2><MediaPicker items={media} multiple selected={media.filter((row)=>images.some((image)=>image.url===row.url))} onSelect={addImages}/></div>{images.map((image,index)=><div className="admin-image-row" key={`${image.url}-${index}`}><Image src={image.url} alt={image.alt||""} width={68} height={68}/><label>Teks alternatif<input value={image.alt} onChange={(e)=>setImages(images.map((row,i)=>i===index?{...row,alt:e.target.value}:row))}/></label><label className="admin-check"><input type="radio" checked={image.isPrimary} onChange={()=>setImages(images.map((row,i)=>({...row,isPrimary:i===index})))}/> Gambar utama</label><label className="admin-check"><input type="checkbox" checked={image.blendMultiply} onChange={(e)=>setImages(images.map((row,i)=>i===index?{...row,blendMultiply:e.target.checked}:row))}/> Latar putih</label><div><button type="button" className="icon-button" disabled={!index} onClick={()=>{const n=[...images];[n[index-1],n[index]]=[n[index],n[index-1]];setImages(n);}}>↑</button><button type="button" className="icon-button" disabled={index===images.length-1} onClick={()=>{const n=[...images];[n[index+1],n[index]]=[n[index],n[index+1]];setImages(n);}}>↓</button><button type="button" className="danger-button" onClick={()=>setImages(images.filter((_,i)=>i!==index))}>Hapus</button></div></div>)}</section>
    <section className="admin-subsection"><div className="admin-section-head"><h2>Varian dan stok</h2><button type="button" className="secondary-button" onClick={()=>setVariants([...variants,{name:"XL",price:249000,compareAtPrice:"",stock:3,sku:"",sortOrder:variants.length,isActive:true}])}>Tambah varian</button></div>{variants.map((row,index)=><div className="admin-variant-row" key={index}><label>Ukuran<input value={row.name} onChange={(e)=>setVariants(variants.map((r,i)=>i===index?{...r,name:e.target.value}:r))}/></label><label>Harga<input type="number" min="0" value={row.price} onChange={(e)=>setVariants(variants.map((r,i)=>i===index?{...r,price:Number(e.target.value)}:r))}/><Link className="secondary-button" href={`/admin/qris?amount=${row.price}`}>Tambah QRIS untuk harga ini</Link></label><label>Harga coret<input type="number" min="0" value={row.compareAtPrice} onChange={(e)=>setVariants(variants.map((r,i)=>i===index?{...r,compareAtPrice:e.target.value?Number(e.target.value):""}:r))}/></label><label>Stok<input type="number" min="0" value={row.stock} onChange={(e)=>setVariants(variants.map((r,i)=>i===index?{...r,stock:Number(e.target.value)}:r))}/></label><label>SKU<input value={row.sku} onChange={(e)=>setVariants(variants.map((r,i)=>i===index?{...r,sku:e.target.value}:r))}/></label><label className="admin-check"><input type="checkbox" checked={row.isActive} onChange={(e)=>setVariants(variants.map((r,i)=>i===index?{...r,isActive:e.target.checked}:r))}/> Aktif</label><div><button type="button" className="icon-button" disabled={!index} onClick={()=>{const n=[...variants];[n[index-1],n[index]]=[n[index],n[index-1]];setVariants(n);}}>↑</button><button type="button" className="icon-button" disabled={index===variants.length-1} onClick={()=>{const n=[...variants];[n[index+1],n[index]]=[n[index],n[index+1]];setVariants(n);}}>↓</button><button type="button" className="danger-button" onClick={()=>setVariants(variants.filter((_,i)=>i!==index))}>Hapus</button></div></div>)}</section>
    <SeoPanel entityType={"PRODUCT" as SeoEntityType} entityId={slug} title={name} description={shortDescription} slug={slug} content={`${shortDescription} ${description}`} images={images} media={media} initial={initial?.seo}/>
    <div className="admin-form-actions"><button className="buy-button" type="submit">Simpan produk</button>{initial&&<ConfirmButton message="Hapus produk ini? Jika sudah ada pesanan, produk harus diarsipkan sebagai Draf." action={async()=>{const result=await deleteProduct(initial.id);if(result.error)window.alert(result.error);else window.location.href="/admin/produk?success=Produk%20dihapus";}}>Hapus produk</ConfirmButton>}</div>
  </form>;
}
