"use client";
import { useState } from "react";
import Image from "next/image";
import imageCompression from "browser-image-compression";
import { createClient } from "@/lib/supabase/client";
import { qrisUploadUrl, prepareOrderQris } from "@/app/admin/payments-actions";
import { formatRupiah } from "@/lib/money";
export function AdminOrderQris({ orderId, amount }: { orderId: string; amount: number }) {
 const [path,setPath]=useState(""); const [preview,setPreview]=useState(""); const [label,setLabel]=useState(""); const [save,setSave]=useState(true); const [message,setMessage]=useState("");
 async function upload(file?:File){if(!file)return;try{if(!["image/png","image/jpeg","image/webp"].includes(file.type)){setMessage("Pilih gambar PNG, JPG, atau WebP.");return}if(file.size>20*1024*1024){setMessage("File sumber terlalu besar untuk diproses, maksimal 20 MB.");return}const image=await imageCompression(file,{maxSizeMB:1,maxWidthOrHeight:1600,useWebWorker:true,fileType:"image/webp"});if(image.size>1024*1024){setMessage("Hasil kompresi terlalu besar. Pilih gambar di bawah 1 MB.");return}const signed=await qrisUploadUrl({type:image.type,size:image.size});if("error"in signed&&signed.error){setMessage(signed.error);return}if(!("path"in signed)||typeof signed.path!=="string"||typeof signed.token!=="string"){setMessage("Tautan unggah QRIS belum tersedia.");return}const {error}=await createClient().storage.from("qris").uploadToSignedUrl(signed.path,signed.token,image,{contentType:image.type});if(error){console.error("[AdminOrderQris.upload]",{message:error.message,code:error.name});setMessage("Upload ke Supabase gagal. Pastikan bucket qris tersedia dan coba kembali.");return}setPath(signed.path);setPreview(URL.createObjectURL(image));}catch{setMessage("Gambar QRIS gagal diproses atau diunggah. Pilih PNG, JPG, atau WebP maksimal 20 MB.");}}
 return <section className="admin-card admin-form"><h2>Siapkan QRIS untuk {formatRupiah(amount)}</h2><label>Gambar QRIS (PNG, JPG, atau WebP)<input type="file" accept="image/png,image/jpeg,image/webp" onChange={(e)=>void upload(e.target.files?.[0])}/></label>{preview&&<Image src={preview} alt="Pratinjau QRIS" width={180} height={180} unoptimized style={{objectFit:"contain"}}/>}<label>Label opsional<input value={label} onChange={(e)=>setLabel(e.target.value)}/></label><label className="admin-check"><input type="checkbox" checked={save} onChange={(e)=>setSave(e.target.checked)}/> Simpan ke pustaka</label><button className="buy-button" disabled={!path} onClick={async()=>{const result=await prepareOrderQris(orderId,path,label,save);setMessage(result.error??"QRIS siap untuk pelanggan.");if(!result.error)window.location.reload();}}>Simpan dan kirim QRIS</button>{message&&<p role="status">{message}</p>}</section>;
}
