"use client";
import { useState } from "react";
import Image from "next/image";
import { saveCategory, deleteCategory } from "@/app/admin/actions";
import { ConfirmButton, MediaPicker, type MediaOption } from "@/components/admin-ui";
import { SeoPanel } from "@/components/seo/seo-panel";
export function AdminCategoryForm({ rows, media, editing, seo, seoScores }: { rows: {id:string;name:string;slug:string;description:string|null;imageUrl:string|null;sortOrder:number;isActive:boolean;productCount:number}[]; media:MediaOption[]; editing?:string; seo?:any; seoScores?:Record<string,{seo:number;reading:number}> }) {
 const category=rows.find((row)=>row.id===editing); const [name,setName]=useState(category?.name??""); const [slug,setSlug]=useState(category?.slug??""); const [edited,setEdited]=useState(Boolean(category)); const [imageUrl,setImageUrl]=useState(category?.imageUrl??""); const [description,setDescription]=useState(category?.description??"");
 const slugify=(value:string)=>value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
 return <><form action={saveCategory} className="admin-card admin-form"><input type="hidden" name="id" value={category?.id??""}/><input type="hidden" name="imageUrl" value={imageUrl}/><div className="admin-form-grid"><label>Nama kategori<input required name="name" value={name} onChange={(e)=>{setName(e.target.value);if(!edited)setSlug(slugify(e.target.value));}}/></label><label>Slug<input required name="slug" value={slug} onChange={(e)=>{setEdited(true);setSlug(slugify(e.target.value));}}/></label><label>Deskripsi<textarea name="description" rows={3} value={description} onChange={e=>setDescription(e.target.value)}/></label><label>Urutan<input type="number" min="0" name="sortOrder" defaultValue={category?.sortOrder??rows.length}/></label><label className="admin-check"><input type="checkbox" name="isActive" defaultChecked={category?.isActive??true}/> Aktif</label><label>Gambar kategori<div className="admin-inline"><MediaPicker items={media} onSelect={(items)=>setImageUrl(items[0]?.url??"")}/>{imageUrl&&<Image className="admin-thumb" src={imageUrl} alt="Pratinjau gambar kategori" width={48} height={48}/>}</div></label></div><SeoPanel entityType="CATEGORY" entityId={slug} title={name} description={description} slug={slug} content={description} images={imageUrl?[{url:imageUrl,alt:media.find(item=>item.url===imageUrl)?.alt||""}]:[]} media={media} initial={seo}/><button className="buy-button">{category?"Simpan perubahan":"Tambah kategori"}</button></form><section className="admin-card"><h2>Kategori tersedia</h2><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Nama</th><th>Slug</th><th>Produk</th><th>Urutan</th><th>Status</th><th>SEO</th><th>Baca</th><th>Aksi</th></tr></thead><tbody>{rows.map((row)=><tr key={row.id}><td>{row.name}</td><td>{row.slug}</td><td>{row.productCount}</td><td>{row.sortOrder}</td><td>{row.isActive?"Aktif":"Nonaktif"}</td><td><span className={`seo-light ${(seoScores?.[row.slug]?.seo??0)>=.75?"good":(seoScores?.[row.slug]?.seo??0)>=.45?"warn":"bad"}`}>{Math.round((seoScores?.[row.slug]?.seo??0)*100)}%</span></td><td><span className={`seo-light ${(seoScores?.[row.slug]?.reading??0)>=.75?"good":(seoScores?.[row.slug]?.reading??0)>=.45?"warn":"bad"}`}>{Math.round((seoScores?.[row.slug]?.reading??0)*100)}%</span></td><td className="admin-actions"><a className="secondary-button" href={`/admin/kategori?edit=${row.id}`}>Ubah</a>{row.productCount===0&&<ConfirmButton message={`Hapus kategori “${row.name}”?`} action={async()=>{const result=await deleteCategory(row.id);if(result.error)window.alert(result.error);else window.location.href="/admin/kategori?success=Kategori%20dihapus";}}>Hapus</ConfirmButton>}</td></tr>)}</tbody></table></div></section></>;
}

