"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import Image from "next/image";
import imageCompression from "browser-image-compression";
import { createClient } from "@/lib/supabase/client";
import { qrisUploadUrl, saveQrisAsset } from "@/app/admin/payments-actions";
type Initial={id:string;amount:number;imagePath:string;label:string|null;isActive:boolean};
export function AdminQrisForm({ amount, initial, storageUrl }: { amount?: number; initial?: Initial; storageUrl?: string }) {
 const router=useRouter();const [path,setPath]=useState(initial?.imagePath??""); const [preview,setPreview]=useState(initial&&storageUrl?`${storageUrl}/storage/v1/object/public/qris/${initial.imagePath}`:""); const [error,setError]=useState(""); const [success,setSuccess]=useState(""); const [busy,setBusy]=useState(false);
 async function upload(file?:File){if(!file)return;setBusy(true);setError("");setSuccess("");try{if(!["image/png","image/jpeg","image/webp"].includes(file.type)){setError("Pilih gambar PNG, JPG, atau WebP.");return}if(file.size>20*1024*1024){setError("File sumber terlalu besar untuk diproses, maksimal 20 MB.");return}const compressed=await imageCompression(file,{maxSizeMB:1,maxWidthOrHeight:1600,useWebWorker:true,fileType:"image/webp"});if(compressed.size>1024*1024){setError("Hasil kompresi masih terlalu besar. Pilih gambar yang lebih kecil (maksimal 1 MB).");return}const signed=await qrisUploadUrl({type:compressed.type,size:compressed.size});if("error"in signed&&signed.error){setError(signed.error);return}if(!("path"in signed)||typeof signed.path!=="string"||typeof signed.token!=="string"){setError("Tautan unggah QRIS belum tersedia.");return}const {error:uploadError}=await createClient().storage.from("qris").uploadToSignedUrl(signed.path,signed.token,compressed,{contentType:compressed.type});if(uploadError){console.error("[AdminQrisForm.upload]",{message:uploadError.message,code:uploadError.name});throw new Error("Upload ke Supabase gagal. Pastikan bucket qris tersedia dan coba kembali.")}setPath(signed.path);setPreview(URL.createObjectURL(compressed));}catch(e){setError(e instanceof Error?e.message:"Gambar belum dapat diunggah. Coba kembali.");}finally{setBusy(false)}}
 async function save(formData:FormData){setBusy(true);setError("");setSuccess("");try{const result=await saveQrisAsset(formData);if(result.error){setError(result.error);return}setSuccess("QRIS berhasil disimpan.");router.refresh()}catch{setError("QRIS gagal disimpan. Coba kembali; jika berulang, hubungi pengelola sistem.")}finally{setBusy(false)}}
 return <form action={save} className="admin-card admin-form"><h2>{initial?"Ubah QRIS":"Tambah QRIS"}</h2>{initial&&<input type="hidden" name="id" value={initial.id}/>}<label>Nominal (Rp)<input type="number" name="amount" min="1" required defaultValue={initial?.amount??amount}/></label><label>Label<input name="label" maxLength={120} defaultValue={initial?.label??""} placeholder="QRIS Dana"/></label><label>Gambar QRIS (PNG, JPG, atau WebP)<input type="file" accept="image/png,image/jpeg,image/webp" required={!path} onChange={(e)=>void upload(e.target.files?.[0])}/></label>{busy&&<p role="status">{path?"Menyimpan QRIS…":"Mengompres dan mengunggah gambar…"}</p>}{error&&<p className="admin-error" role="alert">{error}</p>}{success&&<p role="status">{success}</p>}{preview&&<Image src={preview} alt="Pratinjau QRIS" width={180} height={180} unoptimized style={{objectFit:"contain"}}/>}<input type="hidden" name="imagePath" value={path}/><label className="admin-check"><input type="checkbox" name="isActive" defaultChecked={initial?.isActive??true}/> Aktif</label><button className="buy-button" disabled={busy||!path}>Simpan QRIS</button></form>;
}
