"use client";

import { useState, useTransition, type FormEvent } from "react";
import Image from "next/image";
import imageCompression from "browser-image-compression";
import { createReviewPhotoUploadUrl, saveProductReview } from "@/app/ulasan/produk/actions";
import { createClient } from "@/lib/supabase/client";

type Photo = { id?: string; path: string; url: string };
type Review = { id: string; displayName: string; showFullName: boolean; rating: number; body: string; createdAt: Date; photos: Photo[] };
export function ProductReviewForm({ orderItemId, token, displayName, review, canEdit }: { orderItemId: string; token?: string; displayName: string; review?: Review | null; canEdit: boolean }) {
  const [rating,setRating]=useState(review?.rating??5); const [body,setBody]=useState(review?.body??""); const [name,setName]=useState(review?.displayName??displayName);
  const [showName,setShowName]=useState(review?.showFullName??false); const [photos,setPhotos]=useState<Photo[]>(review?.photos??[]);
  const [message,setMessage]=useState(""); const [busy,start]=useTransition(); const [uploading,setUploading]=useState(false);
  async function addFiles(files:FileList|null){if(!files?.length)return;if(photos.length+files.length>5){setMessage("Maksimal 5 foto untuk satu ulasan.");return;}setUploading(true);setMessage("");try{for(const original of Array.from(files)){if(!["image/jpeg","image/png","image/webp"].includes(original.type))throw new Error("Foto harus JPG, PNG, atau WebP.");const compressed=await imageCompression(original,{maxSizeMB:4.8,maxWidthOrHeight:1600,useWebWorker:true,fileType:"image/webp"});if(compressed.size>5*1024*1024)throw new Error("Setiap foto maksimal 5 MB.");const signed=await createReviewPhotoUploadUrl(orderItemId,token,{name:original.name,type:original.type,size:original.size});const {error}=await createClient().storage.from("reviews").uploadToSignedUrl(signed.path,signed.token,compressed,{contentType:"image/webp"});if(error)throw new Error("Foto belum dapat diunggah.");setPhotos((old)=>[...old,{path:signed.path,url:URL.createObjectURL(compressed)}]);}}catch(error){setMessage(error instanceof Error?error.message:"Foto belum dapat diunggah.");}finally{setUploading(false);}}
  function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);form.set("orderItemId",orderItemId);if(token)form.set("token",token);form.set("photos",JSON.stringify(photos.map((photo)=>photo.path)));if(review)form.set("reviewId",review.id);start(async()=>{const result=await saveProductReview(form);setMessage(result.message??result.error??"Ulasan belum dapat disimpan.");if(result.ok){setBody("");setPhotos([]);setShowName(false);}});}
  function keyboard(event:React.KeyboardEvent){if(event.key==="ArrowRight"||event.key==="ArrowUp"){event.preventDefault();setRating((value)=>Math.min(5,value+1));}else if(event.key==="ArrowLeft"||event.key==="ArrowDown"){event.preventDefault();setRating((value)=>Math.max(1,value-1));}}
  if(!canEdit&&review)return <p className="product-review-locked">Ulasan sudah dikirim dan masa ubah 7 hari telah berakhir.</p>;
  return <form className="product-review-form" onSubmit={submit}><label>Nama yang ditampilkan<input name="displayName" required minLength={2} maxLength={60} value={name} onChange={(e)=>setName(e.target.value)}/></label><div className="review-name-choice"><input type="checkbox" id={"show-name-"+orderItemId} name="showFullName" checked={showName} onChange={(e)=>setShowName(e.target.checked)}/><label htmlFor={"show-name-"+orderItemId}>Tampilkan nama lengkap saya</label></div><fieldset className="review-star-field"><legend>Penilaian</legend><div role="radiogroup" aria-label="Pilih rating bintang" onKeyDown={keyboard}>{[1,2,3,4,5].map((value)=><button key={value} type="button" role="radio" aria-checked={rating===value} aria-label={value+" dari 5 bintang"} tabIndex={rating===value?0:-1} className={value<=rating?"is-active":""} onClick={()=>setRating(value)}>★</button>)}</div><input type="hidden" name="rating" value={rating}/></fieldset><label>Ulasan<textarea name="body" required minLength={10} maxLength={1000} rows={5} value={body} onChange={(e)=>setBody(e.target.value)} placeholder="Ceritakan pengalamanmu dengan produk ini."/></label><small>{body.length}/1000 karakter</small><label>Foto produk<input type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={uploading||photos.length>=5} onChange={(e)=>void addFiles(e.target.files)}/></label><p>Maksimal 5 foto · JPG, PNG, atau WebP · dikompres otomatis hingga 5 MB per foto.</p>{uploading&&<p role="status">Foto sedang diunggah…</p>}{photos.length>0&&<div className="review-photo-previews">{photos.map((photo,index)=><div key={photo.path}><Image src={photo.url} alt={"Foto ulasan "+(index+1)} width={92} height={92} unoptimized/><button type="button" aria-label={"Hapus foto "+(index+1)} onClick={()=>setPhotos((items)=>items.filter((_,i)=>i!==index))}>×</button></div>)}</div>}{message&&<p role="status" className="form-message">{message}</p>}<button className="buy-button" disabled={busy||uploading}>{busy?"Menyimpan…":review?"Simpan perubahan":"Kirim ulasan"}</button></form>;
}
