"use client";
import Image from "next/image";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { toggleReviewHelpful } from "@/app/ulasan/produk/actions";

type Photo = { id: string; url: string; path: string; sortOrder: number };
type Review = { id: string; displayName: string; rating: number; body: string; helpfulCount: number; voted: boolean; sellerReply: string | null; sellerReplyAt: Date | null; createdAt: Date; orderItem: { variantName: string }; photos: Photo[] };
type Data = { average: number; ratingCount: number; distribution: Record<number, number>; reviews: Review[]; total: number; page: number; pageCount: number };

export function ProductReviewSection({ data, slug }: { data: Data; slug: string }) {
 const search=useSearchParams(); const rating=search.get("rating"); const photos=search.get("foto")==="1"; const sort=search.get("urut")==="membantu"?"membantu":"terbaru";
 function href(values:Record<string,string|null>){const params=new URLSearchParams(search.toString());for(const [key,value] of Object.entries(values)){if(value)params.set(key,value);else params.delete(key);}return "/produk/"+slug+"?"+params.toString()+"#ulasan";}
 return <section className="floating-panel product-reviews" id="ulasan" aria-labelledby="product-reviews-title"><header className="product-reviews-heading"><div><p className="eyebrow">Pengalaman pelanggan</p><h2 id="product-reviews-title">Ulasan pembeli</h2></div><div className="review-average"><strong>{data.average.toFixed(1)}</strong><span aria-label={data.average.toFixed(1)+" dari 5 bintang"}>★★★★★</span><small>{data.ratingCount} ulasan</small></div></header>
  <div className="review-distribution">{[5,4,3,2,1].map((value)=>{const count=data.distribution[value]??0;const width=data.ratingCount?count/data.ratingCount*100:0;return <div key={value}><span>{value} ★</span><span className="review-bar"><i style={{width:width+"%"}}/></span><small>{count}</small></div>;})}</div>
  <nav className="review-filters" aria-label="Filter ulasan"><Link className={!rating&&!photos?"active":""} href={href({rating:null,foto:null,reviewPage:null})}>Semua</Link><Link className={photos?"active":""} href={href({foto:"1",reviewPage:null})}>Dengan foto</Link>{[5,4,3,2,1].map((value)=><Link key={value} className={rating===String(value)?"active":""} href={href({rating:String(value),reviewPage:null})}>{value} bintang</Link>)}<span className="review-sort"><Link className={sort==="terbaru"?"active":""} href={href({urut:null,reviewPage:null})}>Terbaru</Link><Link className={sort==="membantu"?"active":""} href={href({urut:"membantu",reviewPage:null})}>Paling membantu</Link></span></nav>
  {data.reviews.length?<div className="product-review-list">{data.reviews.map((review)=><article className="product-review-card" key={review.id}><div className="product-review-card-head"><span className="product-review-stars" aria-label={review.rating+" dari 5 bintang"}>{"★".repeat(review.rating)}{"☆".repeat(5-review.rating)}</span><strong>{review.displayName}</strong><span className="verified-label">Pembeli terverifikasi</span></div><div className="product-review-meta"><span>Ukuran {review.orderItem.variantName}</span><time dateTime={review.createdAt.toISOString()}>{new Intl.DateTimeFormat("id-ID",{dateStyle:"long"}).format(review.createdAt)}</time></div><p>{review.body}</p>{review.photos.length>0&&<ReviewPhotos photos={review.photos}/>}{review.sellerReply&&<div className="seller-reply"><strong>Balasan penjual</strong><p>{review.sellerReply}</p></div>}<HelpfulButton reviewId={review.id} count={review.helpfulCount} initialVoted={review.voted}/></article>)}</div>:<p className="review-empty">Belum ada ulasan untuk pilihan ini.</p>}
  {data.page<data.pageCount&&<Link className="secondary-button review-load-more" href={href({reviewPage:String(data.page+1)})}>Muat lebih banyak ulasan</Link>}
 </section>;
}

function HelpfulButton({reviewId,count,initialVoted}:{reviewId:string;count:number;initialVoted:boolean}){const [voted,setVoted]=useState(initialVoted);const [value,setValue]=useState(count);const [busy,setBusy]=useState(false);const router=useRouter();useEffect(()=>{setVoted(initialVoted);setValue(count);},[initialVoted,count]);return <button type="button" className={"review-helpful"+(voted?" is-voted":"")} disabled={busy} aria-pressed={voted} onClick={async()=>{setBusy(true);const result=await toggleReviewHelpful(reviewId);if("count"in result){setVoted(result.voted);setValue(result.count);router.refresh();}setBusy(false);}}>Membantu ({value})</button>}

function ReviewPhotos({photos}:{photos:Photo[]}){const [selected,setSelected]=useState<number|null>(null);const [touch,setTouch]=useState<number|null>(null);const move=useCallback((delta:number)=>{setSelected((current)=>current===null?null:(current+delta+photos.length)%photos.length);},[photos.length]);useEffect(()=>{if(selected===null)return;function key(event:KeyboardEvent){if(event.key==="Escape")setSelected(null);if(event.key==="ArrowRight")move(1);if(event.key==="ArrowLeft")move(-1);}window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key);},[selected,move]);return <><div className="product-review-photos">{photos.map((photo,index)=><button type="button" key={photo.id} onClick={()=>setSelected(index)} aria-label={"Perbesar foto ulasan "+(index+1)}><Image src={photo.url} alt={"Foto ulasan pelanggan "+(index+1)} width={92} height={92}/></button>)}</div>{selected!==null&&<div className="review-lightbox" role="dialog" aria-modal="true" aria-label="Foto ulasan" tabIndex={-1} onClick={()=>setSelected(null)} onTouchStart={(event)=>setTouch(event.touches[0].clientX)} onTouchEnd={(event)=>{if(touch!==null&&Math.abs(event.changedTouches[0].clientX-touch)>45)move(event.changedTouches[0].clientX<touch?1:-1);setTouch(null);}}><button type="button" className="review-lightbox-close" aria-label="Tutup foto" onClick={()=>setSelected(null)}>×</button><button type="button" className="review-lightbox-prev" aria-label="Foto sebelumnya" onClick={(event)=>{event.stopPropagation();move(-1);}}>‹</button><Image src={photos[selected].url} alt={"Foto ulasan "+(selected+1)} width={1200} height={1000} onClick={(event)=>event.stopPropagation()}/><button type="button" className="review-lightbox-next" aria-label="Foto berikutnya" onClick={(event)=>{event.stopPropagation();move(1);}}>›</button></div>}</>}

