"use client";
import dynamic from "next/dynamic";
import { useState } from "react";
import { MediaPicker, type MediaOption } from "@/components/admin-ui";
import { saveBlogPost } from "@/app/admin/blog/actions";
import { SeoPanel } from "@/components/seo/seo-panel";
import type { SeoMeta } from "@prisma/client";
const RichTextEditor = dynamic(() => import("@/components/cms/rich-text-editor"), { ssr: false, loading: () => <p>Memuat editor teks…</p> });
type Post = { id: string; slug: string; title: string; excerpt: string; coverImageUrl: string | null; coverAlt: string | null; content: string; status: string; publishedAt: Date | null };
const slugify = (value: string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
export function AdminBlogEditor({ post, media, seo }: { post?: Post; media: MediaOption[]; seo?:SeoMeta|null }) {
  const [title,setTitle]=useState(post?.title??""); const [slug,setSlug]=useState(post?.slug??""); const [excerpt,setExcerpt]=useState(post?.excerpt??""); const [cover,setCover]=useState(post?.coverImageUrl??""); const [coverAlt,setCoverAlt]=useState(post?.coverAlt??""); const [content,setContent]=useState(post?.content??"<p>Tulis artikel di sini.</p>");
  return <form action={saveBlogPost} className="admin-card cms-blog-form">{post&&<input type="hidden" name="id" value={post.id}/>}<input type="hidden" name="coverImageUrl" value={cover}/><input type="hidden" name="coverAlt" value={coverAlt}/><input type="hidden" name="content" value={content}/><label>Judul<input className="admin-input" name="title" value={title} onChange={(e)=>{setTitle(e.target.value);if(!post)setSlug(slugify(e.target.value));}} required maxLength={180}/></label><label>Slug<input className="admin-input" name="slug" value={slug} onChange={(e)=>setSlug(e.target.value)} required/></label><label>Ringkasan<textarea className="admin-input" name="excerpt" value={excerpt} onChange={e=>setExcerpt(e.target.value)} required maxLength={500}/></label><div className="cms-fields"><MediaPicker items={media} onSelect={(items)=>{if(items[0]){setCover(items[0].url);setCoverAlt(items[0].alt);}}}/><label>Teks alternatif sampul<input className="admin-input" value={coverAlt} onChange={(e)=>setCoverAlt(e.target.value)}/></label></div>{cover&&<p className="cms-cover-preview">Sampul dipilih: {cover}</p>}<label>Isi artikel<RichTextEditor value={content} onChange={setContent}/></label><label>Jadwal terbit<input className="admin-input" type="datetime-local" name="publishedAt" defaultValue={post?.publishedAt?.toISOString().slice(0,16)}/></label><SeoPanel entityType="BLOG_POST" entityId={slug} title={title} description={excerpt} slug={slug} content={content} images={cover?[{url:cover,alt:coverAlt}]:[]} media={media} initial={seo}/><div className="cms-save-bar"><button className="secondary-button" name="submitStatus" value="DRAFT">Simpan draf</button><button className="buy-button" name="submitStatus" value="PUBLISHED">Terbitkan</button></div></form>;
}
