import Link from "next/link";
import { requireAdmin } from "@/lib/admin";
import { prisma } from "@/lib/prisma";
import { createPage } from "@/app/admin/halaman/actions";
import { deletePage } from "@/app/admin/halaman/actions";
import { DeleteConfirmForm } from "@/components/cms/delete-confirm-form";
import { analyzeSeo } from "@/lib/seo-analysis";

export default async function AdminPages() {
  await requireAdmin();
  const pages = await prisma.page.findMany({ orderBy: [{ isSystem: "desc" }, { title: "asc" }] });
  const seoRows=await prisma.seoMeta.findMany({where:{entityType:"PAGE",entityId:{in:pages.map(page=>page.slug)}}});const seoMap=new Map(seoRows.map(row=>[row.entityId,row]));
  return <><div className="admin-page-heading"><div><p className="eyebrow">Konten situs</p><h1>Halaman</h1></div></div><form action={createPage} className="admin-card cms-create-page"><h2>Tambah halaman</h2><label>Judul<input className="admin-input" name="title" required maxLength={150}/></label><label>Slug<input className="admin-input" name="slug" required pattern="[a-z0-9]+(-[a-z0-9]+)*" placeholder="cerita-kami"/></label><button className="buy-button">Buat halaman</button><p>Slug sistem seperti toko, produk, akun, dan admin tidak dapat digunakan.</p></form><section className="admin-card"><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Judul</th><th>Slug</th><th>Status</th><th>SEO</th><th>Baca</th><th>Diperbarui</th><th></th></tr></thead><tbody>{pages.map((page)=>{const meta=seoMap.get(page.slug);const blocks=Array.isArray(page.blocks)?page.blocks as any[]:[];const content=blocks.map(block=>block.type==="teks"?block.html:block.type==="judul"?`<h2>${block.text}</h2>`:JSON.stringify(block)).join(" ");const analysis=analyzeSeo({keyword:meta?.focusKeyword||"",title:meta?.seoTitle||page.title,description:meta?.metaDescription||page.title,slug:page.slug,content,kind:"page",imageAlts:blocks.flatMap(block=>block.type==="gambar"?[block.alt]:block.type==="galeri"?block.items.map((item:any)=>item.alt):[])});return <tr key={page.id}><td>{page.title}{page.isSystem&&<small> · Halaman bawaan</small>}</td><td>/{page.slug}</td><td>{page.status==="PUBLISHED"?"Terbit":"Draf"}</td><td><span className={`seo-light ${analysis.seoScore>=.75?"good":analysis.seoScore>=.45?"warn":"bad"}`}>{Math.round(analysis.seoScore*100)}%</span></td><td><span className={`seo-light ${analysis.readabilityScore>=.75?"good":analysis.readabilityScore>=.45?"warn":"bad"}`}>{Math.round(analysis.readabilityScore*100)}%</span></td><td>{new Intl.DateTimeFormat("id-ID",{dateStyle:"medium"}).format(page.updatedAt)}</td><td><div className="cms-fields"><Link className="secondary-button" href={`/admin/halaman/${page.id}`}>Ubah</Link>{!page.isSystem&&<DeleteConfirmForm id={page.id} action={deletePage} message="Hapus halaman ini secara permanen?"/>}</div></td></tr>})}</tbody></table></div>{!pages.length&&<p>Jalankan seed untuk membuat halaman bawaan.</p>}</section></>;
}
