import { createElement as h } from "react";
import { Document, Page, Text, View, Image as PdfImage, StyleSheet, renderToBuffer } from "@react-pdf/renderer";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { getCurrentProfile } from "@/lib/auth";
import { safeTokenEqual } from "@/lib/token";

export const runtime = "nodejs";
const styles=StyleSheet.create({page:{padding:36,fontFamily:"Helvetica",fontSize:10,color:"#7a2e3f",backgroundColor:"#fff9fa"},header:{backgroundColor:"#fbcfd6",padding:18,marginBottom:20},title:{fontSize:22,color:"#b3144f",marginBottom:6},row:{flexDirection:"row",justifyContent:"space-between",paddingVertical:6,borderBottomWidth:0.5,borderColor:"#e7a8b7"},section:{marginTop:14,lineHeight:1.5},total:{fontSize:14,color:"#b3144f",marginTop:10},stamp:{position:"absolute",right:40,top:35,fontSize:20,color:"#b3144f",borderWidth:2,borderColor:"#b3144f",padding:8}});
export async function GET(request:Request,{params}:{params:{orderNumber:string}}){
 const url=new URL(request.url);const token=url.searchParams.get("t");const profile=await getCurrentProfile().catch(()=>null);const order=await prisma.order.findUnique({where:{orderNumber:params.orderNumber},include:{invoice:true,items:true}});
 if(!order||!order.invoice)notFound();const isAdmin=profile?.role==="ADMIN";if(!isAdmin&&order.userId!==profile?.id&&!safeTokenEqual(order.accessToken,token))notFound();
 const snapshot=order.invoice.snapshot as any;const store=snapshot.store??{};const customer=snapshot.customer??{};const recipient=snapshot.recipient??{};
 const children=[h(View,{style:styles.header,key:"top"},[store.logoUrl?h(PdfImage,{key:"logo",src:String(store.logoUrl),style:{width:72,height:48,objectFit:"contain"}}):null,h(Text,{style:styles.title,key:"brand"},String(store.name||"radinkacraft")),h(Text,{key:"address"},String(store.address||"")),h(Text,{key:"phone"},String(store.phone||"")),h(Text,{key:"email"},String(store.email||""))]),h(Text,{style:styles.title,key:"inv"},`Invoice ${order.invoice.invoiceNumber}`),h(Text,{key:"date"},`Tanggal: ${new Intl.DateTimeFormat("id-ID",{dateStyle:"long",timeZone:"Asia/Jakarta"}).format(order.invoice.issuedAt)}`),h(View,{style:styles.section,key:"customer"},[h(Text,{key:"c1"},`Pelanggan: ${customer.name||order.customerName} · ${customer.email||order.customerEmail}`),h(Text,{key:"c2"},`Penerima: ${recipient.name||order.recipientName} · ${recipient.phone||order.recipientPhone}`),h(Text,{key:"c3"},`Alamat: ${recipient.address||order.address}, ${recipient.city||order.city} ${recipient.postalCode||""}`),h(Text,{key:"c4"},`Jadwal: ${new Intl.DateTimeFormat("id-ID",{dateStyle:"medium",timeZone:"Asia/Jakarta"}).format(new Date(recipient.deliveryDate||order.deliveryDate))} · ${recipient.deliverySlot||order.deliverySlot}`)]),h(View,{style:styles.section,key:"items"},[h(View,{style:styles.row,key:"head"},[h(Text,{key:"a"},"Produk"),h(Text,{key:"b"},"Harga × jumlah"),h(Text,{key:"c"},"Subtotal")]),...order.items.map((item:any)=>h(View,{style:styles.row,key:item.id},[h(Text,{key:"name"},`${item.productName} · ${item.variantName}`),h(Text,{key:"qty"},`${item.price.toLocaleString("id-ID")} × ${item.qty}`),h(Text,{key:"subtotal"},`Rp ${(item.price*item.qty).toLocaleString("id-ID")}`)]))]),h(View,{style:styles.section,key:"totals"},[h(Text,{style:styles.row,key:"subtotal"},`Subtotal: Rp ${order.subtotal.toLocaleString("id-ID")}`),h(Text,{style:styles.row,key:"shipping"},`Ongkir: Rp ${order.shippingFee.toLocaleString("id-ID")}`),h(Text,{style:styles.total,key:"total"},`Total: Rp ${order.total.toLocaleString("id-ID")}`),h(Text,{key:"method"},`Metode pembayaran: ${order.paymentMethod==="BANK"?"Transfer bank":"QRIS Dana"}`)]),h(Text,{style:styles.stamp,key:"stamp"},"LUNAS"),h(Text,{style:styles.section,key:"footer"},String(store.invoiceFooter||"Terima kasih telah berbelanja di radinkacraft."))];
 const pdf=await renderToBuffer(h(Document,null,h(Page,{size:"A4",style:styles},children)));return new Response(new Uint8Array(pdf),{headers:{"Content-Type":"application/pdf","Content-Disposition":`attachment; filename="${order.invoice.invoiceNumber}.pdf"`,"Cache-Control":"private, no-store"}});
}
